export const SEARCH_ACTION = "SEARCH_ACTION";
//User Action type
export const LOGIN_FAILS = "LOGIN_FAILS"; 
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
//Product Action type
export const GET_PRODUCTS_BEGIN = "GET_PRODUCTS_BEGIN";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILS = "GET_PRODUCTS_FAILS";
//
export const GET_PRODUCT_DETAILS_SUCCESS = "GET_PRODUCT_DETAILS_SUCCESS";
export const GET_PRODUCT_DETAILS_FAILS = "GET_PRODUCT_DETAILS_FAILS";
export const GET_PRODUCT_DETAILS_BEGIN = "GET_PRODUCT_DETAILS_BEGIN";
